### ISSUE TITLE
Invalid Directive error message

### ISSUE THREAD

**Issue by LukePrior** [alexa-labs/skill-sample-nodejs-level-up-riddles#1]
Your skill is sending APL documents to devices that do not support APL.

lease update your skill to check for APL support in the skill request prior to sending APL documents in the skill response. For devices that don’t support APL, you can choose to either use display templates or implement experiences just with voice.

I received this when submitting my app made from this sample.

https://forums.developer.amazon.com/questions/191703/invalid-directive-error-message.html?childToView=191829

If anyone could tell me how to implement this it would be great!

Thanks

**Comment by arunjeetsingh** [comment]
Repo maintainer(s), please see alexa-labs/skill-sample-nodejs-firetv-vlogs#3 for how to fix this issue. 
@Uskompuf , I responded to your forum post as well.

**Comment by CamiWilliams** [comment]
Done! Added supportsAPL function to repo.
